### PR TITLE
refactor: apply `webpack-defaults`

### LINKED ISSUE #5: webpack-defaults upgrade
Addition of `webpack-defaults` & associated refactoring as a part of the next `Major` release

Issue exists for status tracking across the organization. 

>Please do not close

### LINKED ISSUE #6: Standardize README

### PR DESCRIPTION
**Pull request by michael-ciniawsky**
### `Noteable Changes`

- `webpack-defaults@latest`
- adds test(s)

### `Issues`

- Fixes #5 
- Fixes #6

### CODE REVIEW

**Comment by michael-ciniawsky** [comment]
CI needs to be enabled for this repo aswell please :)

**Comment by d3viant0ne** [comment]
@michael-ciniawsky - Travis / Appveyor / Codecov are now all enabled.

**Comment by michael-ciniawsky** [comment]
@d3viant0ne  Thx

**Comment by shellscape** [comment]
Superseded by #11

**Pull request closed without merging**
